import Phaser from 'phaser';
import type {ModelDefinition,ResourceKey} from '../data/content';
import type {Career} from '../core/career';
import type {WorkstationData} from '../data/v1Catalog';
import {agentCanProcess,answerAddOn,createProject,decideCustomer,offerAddOn,processProject,processingMs,runtimeLevel,upgradeEffects,type AgentState,type CustomerDecision,type ProjectBox} from '../core/v1Runtime';
import {SeededRandom} from '../core/random';

export interface RunResult {score:number;stars:number;delivered:number;satisfaction:number;complaints:string[]}
const icons:Record<string,string>={counter:'◎',text:'文',search:'搜',document:'表',art:'畫',music:'♪',recording:'聲',studio:'攝',video:'剪',code:'</>',deploy:'雲'};
const colors=[0xffcf66,0x6de4ff,0x76b7ff,0x92d6ca,0xff78bb,0xc995ff,0xff9aa8,0xffb66d,0x89a7ff,0x8bff9d,0x64e3b2];

export class WorkstationScene extends Phaser.Scene{
 private player!:Phaser.GameObjects.Container;private keys!:Record<string,Phaser.Input.Keyboard.Key>;private prompt!:Phaser.GameObjects.Text;private hud!:Phaser.GameObjects.Text;private status!:Phaser.GameObjects.Text;private decision?:Phaser.GameObjects.Container;private target?:Phaser.Math.Vector2;private nearby?:WorkstationData;private box?:ProjectBox;private processing=false;private left:number;private score=0;private delivered=0;private satisfaction=65;private complaints:string[]=[];private loads:Record<ResourceKey,number>={cpu:5,gpu:5,ram:5,context:5,server:12};private readonly runtime;private readonly effects;private readonly rng;private agent:AgentState;
 constructor(private model:ModelDefinition,private career:Career,private levelId:string,seed:number,private finish:(r:RunResult)=>void){super('workstation');this.runtime=runtimeLevel(levelId);this.left=this.runtime.duration;this.effects=upgradeEffects(career);this.rng=new SeededRandom(seed);this.agent={assignment:career.agent.assignment,busy:false,cooldownUntil:0,load:0}}
 create(){this.cameras.main.setBackgroundColor('#07101d');this.add.rectangle(480,390,830,430,0x10243b).setStrokeStyle(5,0x294a67);this.add.text(480,184,`${this.runtime.name} · ${this.runtime.mapId}`,{fontSize:'20px',fontStyle:'bold',color:'#c8f7ff'}).setOrigin(.5);this.makeStations();this.makePlayer();this.hud=this.add.text(24,24,'',{fontFamily:'monospace',fontSize:'14px',color:'#d8f5ff',backgroundColor:'#06131fdd',padding:{x:13,y:10}}).setDepth(900);this.status=this.add.text(480,600,'',{fontSize:'16px',color:'#fff',backgroundColor:'#06131fee',padding:{x:14,y:8},wordWrap:{width:760}}).setOrigin(.5).setDepth(901);this.prompt=this.add.text(480,565,'',{fontSize:'15px',color:'#8cecff'}).setOrigin(.5).setDepth(900);const keyboard=this.input.keyboard!;this.keys=keyboard.addKeys('W,A,S,D,UP,DOWN,LEFT,RIGHT,E,SPACE') as Record<string,Phaser.Input.Keyboard.Key>;keyboard.on('keydown-E',()=>this.interact());keyboard.on('keydown-SPACE',()=>this.interact());this.time.addEvent({delay:1000,loop:true,callback:()=>this.tick()});this.spawnCustomer();this.updateHud()}
 private makeStations(){this.runtime.workstations.forEach((s,index)=>{const cols=this.runtime.workstations.length>7?5:4,row=Math.floor(index/cols),col=index%cols,x=145+col*(670/(cols-1)),y=265+row*135;const c=this.add.container(x,y,[this.add.ellipse(0,34,130,40,0x000000,.35),this.add.rectangle(0,0,118,72,colors[index],.25).setStrokeStyle(3,colors[index]),this.add.text(0,-9,icons[s.id],{fontSize:s.id==='code'?'16px':'24px',fontStyle:'bold',color:'#fff'}).setOrigin(.5),this.add.text(0,48,s.name,{fontSize:'12px',color:'#fff',backgroundColor:'#06131fee',padding:{x:5,y:3}}).setOrigin(.5)]).setSize(130,105).setInteractive({useHandCursor:true});c.on('pointerdown',()=>this.target=new Phaser.Math.Vector2(x,y+55));c.setData('station',s)})}
 private makePlayer(){this.player=this.add.container(480,520,[this.add.ellipse(0,27,52,22,0x000000,.4),this.add.polygon(0,0,[-20,-7,0,-24,20,-7,20,18,0,31,-20,18],this.model.color).setStrokeStyle(3,0xe9fdff),this.add.text(0,-7,'•  •',{fontSize:'12px',color:'#fff'}).setOrigin(.5)]).setDepth(50)}
 update(_:number,delta:number){if(this.left<=0)return;let dx=0,dy=0;if(this.keys.A.isDown||this.keys.LEFT.isDown)dx--;if(this.keys.D.isDown||this.keys.RIGHT.isDown)dx++;if(this.keys.W.isDown||this.keys.UP.isDown)dy--;if(this.keys.S.isDown||this.keys.DOWN.isDown)dy++;if(dx||dy){this.target=undefined;const l=Math.hypot(dx,dy);this.move(dx/l*delta*.2,dy/l*delta*.2)}else if(this.target){const d=Phaser.Math.Distance.Between(this.player.x,this.player.y,this.target.x,this.target.y);if(d<8)this.target=undefined;else{const a=Phaser.Math.Angle.Between(this.player.x,this.player.y,this.target.x,this.target.y);this.move(Math.cos(a)*delta*.2,Math.sin(a)*delta*.2)}}let closest:{station:WorkstationData;distance:number}|undefined;for(const child of this.children.list){if(child instanceof Phaser.GameObjects.Container&&child.getData('station')){const d=Phaser.Math.Distance.Between(this.player.x,this.player.y,child.x,child.y);if(!closest||d<closest.distance)closest={station:child.getData('station'),distance:d}}}this.nearby=closest&&closest.distance<100?closest.station:undefined;this.prompt.setText(this.processing?'設備執行中（不可中途改派）':this.nearby?`E 互動：${this.nearby.name}`:'點設備尋路 · WASD 移動 · E 互動')}
 private move(x:number,y:number){this.player.x=Phaser.Math.Clamp(this.player.x+x,90,870);this.player.y=Phaser.Math.Clamp(this.player.y+y,215,535);this.player.setDepth(Math.round(this.player.y))}
 private spawnCustomer(){if(this.box||this.left<10)return;const recipe=this.rng.pick(this.runtime.recipes),customer=this.rng.pick(this.runtime.customers);this.box=createProject(`box-${this.delivered}`,recipe,customer);this.status.setText(`${customer.name} 帶來「${recipe.name}」。請到櫃台選擇回應。`)}
 private showDecision(){if(!this.box||this.box.accepted||this.decision)return;const choices:[string,CustomerDecision][]=[['接受','accept'],['追問','question'],['提醒限制','limits'],['替代方案','alternative'],['拒絕','reject']];const bg=this.add.rectangle(0,0,700,105,0x06131f,.97).setStrokeStyle(2,0x6de4ff);const children:Phaser.GameObjects.GameObject[]=[bg];choices.forEach(([label,value],i)=>{children.push(this.add.text(-290+i*145,0,label,{fontSize:'15px',color:'#fff',backgroundColor:'#18395a',padding:{x:10,y:10}}).setOrigin(.5).setInteractive({useHandCursor:true}).on('pointerdown',()=>this.choose(value)))});this.decision=this.add.container(480,475,children).setDepth(950)}
 private choose(decision:CustomerDecision){const result=decideCustomer(this.box!,decision);this.satisfaction+=result.satisfaction;this.decision?.destroy();this.decision=undefined;if(!result.accepted){this.box=undefined;this.status.setText(`${result.message}，滿意度 ${result.satisfaction}`);this.time.delayedCall(700,()=>this.spawnCustomer())}else{this.loads.context+=15;this.status.setText(`${result.message}。領取資料箱，第一階段：${this.box!.recipe.runtimeSteps[0].label}`);this.maybeAgent()}this.updateHud()}
 private interact(){if(!this.nearby||this.processing||this.left<=0)return;if(this.nearby.id==='counter'){if(!this.box)return void this.status.setText('目前沒有等待客戶');if(!this.box.accepted)return void this.showDecision();if(!this.box.complete)return void this.status.setText(`不可交付：尚缺 ${this.box.recipe.runtimeSteps.length-this.box.stage} 個階段`);if(this.box.addOn&&!this.box.addOn.accepted)return void this.showAddOn();this.deliver();return}if(!this.box)return void this.status.setText('先到櫃台接收資料箱');const result=processProject(this.box,this.nearby.id,this.nearby.quality);if(!result.ok)return void this.status.setText(result.reason);this.box.stage--;this.box.outputs.pop();this.box.complete=false;this.startProcessing(this.nearby)}
 private startProcessing(station:WorkstationData){this.processing=true;this.loads[station.resource]+=station.cost;this.loads.server+=18;this.status.setText(`${station.name} 鎖定資料箱處理中，不可中途改派`);this.time.delayedCall(processingMs(station,this.model,this.loads.server,this.effects),()=>{const result=processProject(this.box!,station.id,station.quality+this.effects.stability*10);this.processing=false;this.loads[station.resource]=Math.max(5,this.loads[station.resource]-station.cost*.7);this.loads.server=Math.max(12,this.loads.server-14);this.score+=40;this.status.setText(result.reason);this.updateHud()})}
 private showAddOn(){const accept=confirm(`客戶留在櫃台追加：「${this.box!.addOn!.label}」\n接受會重新開啟資料箱；取消代表拒絕並降低滿意度。`);const result=answerAddOn(this.box!,accept);this.satisfaction+=result.satisfaction;this.status.setText(accept?'已接受追加，資料箱重新開啟':'已拒絕追加，客戶不太滿意');if(!accept)this.deliver()}
 private deliver(){if(offerAddOn(this.box!,this.rng.next()))return void this.showAddOn();const avg=this.box!.quality/Math.max(1,this.box!.outputs.length);this.score+=this.box!.recipe.reward+Math.round(avg);this.satisfaction=Math.min(100,this.satisfaction+5);this.delivered++;this.box=undefined;this.loads.context=Math.max(5,this.loads.context-15);this.status.setText('完整交付！結果已寫入生涯紀錄。');this.time.delayedCall(700,()=>this.spawnCustomer());this.updateHud()}
 private maybeAgent(){if(!this.box||!agentCanProcess(this.agent,this.box,this.time.now))return;this.agent.busy=true;this.agent.load=15;this.loads.ram+=15;this.loads.server+=12;this.status.setText(`Agent 自動接手 ${this.agent.assignment} 單步任務`);this.time.delayedCall(3000/Math.max(1,this.effects.agentLevel),()=>{processProject(this.box!,this.agent.assignment as 'text'|'art'|'code',65+this.effects.agentLevel*5);this.agent.busy=false;this.agent.cooldownUntil=this.time.now+5000;this.agent.load=0;this.loads.ram-=10;this.loads.server-=8;this.status.setText('Agent 完成輔助處理，進入冷卻');this.updateHud()})}
 private tick(){if(this.left<=0)return;this.left--;if(this.box)this.box.patience=Math.max(0,this.box.patience-1);for(const key of Object.keys(this.loads) as ResourceKey[])this.loads[key]=Math.max(key==='server'?12:5,this.loads[key]-.7);this.updateHud();if(this.left===0){const t=this.runtime.stars;const stars=this.score>=t[2]?3:this.score>=t[1]?2:this.score>=t[0]?1:0;this.time.delayedCall(250,()=>this.finish({score:this.score,stars,delivered:this.delivered,satisfaction:this.satisfaction,complaints:this.complaints}))}}
 private updateHud(){const meters=(Object.keys(this.loads) as ResourceKey[]).map(k=>`${k.toUpperCase()} ${Math.round(this.loads[k])}/${this.effects.capacity[k]}`).join('  ');const box=this.box?`▣ ${this.box.recipe.name} ${this.box.stage}/${this.box.recipe.runtimeSteps.length}\n已保存：${this.box.outputs.map(o=>o.output).join('、')||'無'}`:'等待新客戶';this.hud.setText(`⏱ ${Math.floor(this.left/60)}:${String(this.left%60).padStart(2,'0')}  SCORE ${this.score}  滿意 ${this.satisfaction}\n${box}\n${meters}\nAgent：${this.agent.busy?'處理中':this.agent.assignment??'休息'} · 槽位 ${this.effects.caseSlots}`)}
}
