import type { Career } from '../core/career';
import { SAVE_VERSION } from '../core/career';
const DB='ai-simulator', STORE='careers';
const open=()=>new Promise<IDBDatabase>((resolve,reject)=>{const request=indexedDB.open(DB,2);request.onupgradeneeded=()=>{if(!request.result.objectStoreNames.contains(STORE))request.result.createObjectStore(STORE,{keyPath:'id'})};request.onsuccess=()=>resolve(request.result);request.onerror=()=>reject(request.error)});
export async function saveCareer(save:Career){const db=await open();await new Promise<void>((resolve,reject)=>{const tx=db.transaction(STORE,'readwrite');tx.objectStore(STORE).put(save);tx.oncomplete=()=>resolve();tx.onerror=()=>reject(tx.error)});db.close()}
export async function loadCareers():Promise<Career[]>{const db=await open();const values=await new Promise<unknown[]>((resolve,reject)=>{const request=db.transaction(STORE).objectStore(STORE).getAll();request.onsuccess=()=>resolve(request.result);request.onerror=()=>reject(request.error)});db.close();return values.map(migrateCareer)}
export async function deleteCareer(id:string){const db=await open();await new Promise<void>((resolve,reject)=>{const tx=db.transaction(STORE,'readwrite');tx.objectStore(STORE).delete(id);tx.oncomplete=()=>resolve();tx.onerror=()=>reject(tx.error)});db.close()}
export function migrateCareer(value:any):Career{if(value?.schemaVersion===SAVE_VERSION)return value as Career;if(value?.schemaVersion===1)return{schemaVersion:2,id:value.id,name:'繼承模型',seed:value.seed,rngState:value.seed,modelId:value.modelId,createdAt:value.completedAt,updatedAt:value.completedAt,era:1,resources:value.bestScore??0,subscribers:0,rating:3.5,complaints:[],levels:value.bestStars?{'era1-01':{stars:value.bestStars,bestScore:value.bestScore,rewardClaims:1}}:{},upgrades:{},agent:{unlocked:false,level:0,assignment:null},endless:{unlocked:false,bestScore:0}};throw new Error('不支援或損壞的存檔格式')}
export function exportCareer(career:Career){return JSON.stringify({format:'ai-simulator-career',exportedAt:new Date().toISOString(),career},null,2)}
export function previewImport(text:string){const parsed=JSON.parse(text);if(parsed.format!=='ai-simulator-career'||!parsed.career)throw new Error('不是 AI Simulator 備份');const career=migrateCareer(parsed.career);return{id:career.id,name:career.name,modelId:career.modelId,updatedAt:career.updatedAt,career}}
