import type { ModelDefinition, ResourceKey } from '../data/content';
import {v1Customers,v1Levels,v1Recipes,v1Workstations,type CustomerData,type LevelData,type RecipeData,type WorkstationData,type WorkstationId} from '../data/v1Catalog';
import type {Career} from './career';

export type CustomerDecision='accept'|'question'|'limits'|'alternative'|'reject';
export interface RuntimeStep {index:number;stationId:WorkstationId;output:string;label:string}
export interface RuntimeRecipe extends RecipeData {runtimeSteps:RuntimeStep[]}
export interface RuntimeLevel extends LevelData {workstations:WorkstationData[];recipes:RuntimeRecipe[];customers:CustomerData[]}
export interface ProjectBox {id:string;recipe:RuntimeRecipe;customer:CustomerData;stage:number;outputs:RuntimeStep[];quality:number;patience:number;accepted:boolean;addOn?:{label:string;accepted?:boolean};complete:boolean}
export interface UpgradeEffects {capacity:Record<ResourceKey,number>;speedMultiplier:number;stability:number;caseSlots:number;agentLevel:number}
export interface AgentState {assignment:string|null;busy:boolean;cooldownUntil:number;load:number}

const byId=<T extends {id:string}>(items:T[],id:string)=>items.find(item=>item.id===id);
export function runtimeRecipe(recipe:RecipeData):RuntimeRecipe{return{...recipe,runtimeSteps:recipe.steps.map((stationId,index)=>{const station=byId(v1Workstations,stationId)!;return{index,stationId,output:station.output,label:`${station.name}：${station.output}`}})}}
export function runtimeLevel(levelId:string):RuntimeLevel{const level=byId(v1Levels,levelId);if(!level)throw new Error('未知關卡');return{...level,workstations:level.stations.map(id=>byId(v1Workstations,id)!),recipes:level.recipeIds.map(id=>runtimeRecipe(byId(v1Recipes,id)!)),customers:level.customerIds.map(id=>byId(v1Customers,id)!)}}
export function isLevelUnlocked(career:Career,level:LevelData){if(level.era>career.era)return false;if(level.index===1)return level.era===1||v1Levels.filter(l=>l.era===level.era-1).every(l=>(career.levels[l.id]?.stars??0)>0);const previous=v1Levels.find(l=>l.era===level.era&&l.index===level.index-1);return !!previous&&(career.levels[previous.id]?.stars??0)>=level.unlockStars}
export function createProject(id:string,recipe:RuntimeRecipe,customer:CustomerData):ProjectBox{return{id,recipe,customer,stage:0,outputs:[],quality:0,patience:customer.patience,accepted:false,complete:false}}
export function decideCustomer(box:ProjectBox,decision:CustomerDecision){let satisfaction=0;if(decision==='accept'){box.accepted=true;satisfaction=box.customer.completeness>=.5?2:-5}else if(decision==='question'){box.accepted=true;box.patience-=6;satisfaction=box.customer.questionTolerance>=.5?10:-8}else if(decision==='limits'){box.accepted=true;satisfaction=box.customer.contradictionChance>.2?8:1}else if(decision==='alternative'){box.accepted=true;satisfaction=box.customer.alternativeTolerance>=.5?8:-6}else{satisfaction=box.customer.patience<40?2:-10}return{accepted:box.accepted,satisfaction,message:decision==='reject'?'已拒絕專案':decision==='question'?'需求已補齊，返工風險降低':'客戶決策已記錄'}}
export function processProject(box:ProjectBox,stationId:WorkstationId,quality:number){if(!box.accepted)return{ok:false,reason:'尚未在櫃台接受此任務'};if(box.complete)return{ok:false,reason:'資料箱成果已齊全，請回櫃台交付'};const expected=box.recipe.runtimeSteps[box.stage];if(expected.stationId!==stationId)return{ok:false,reason:`錯誤工作區：資料箱目前保存「${box.outputs.map(o=>o.output).join('、')||'原始需求'}」，下一階段必須送到 ${byId(v1Workstations,expected.stationId)!.name}`};box.outputs.push(expected);box.stage++;box.quality+=quality;box.complete=box.stage>=box.recipe.runtimeSteps.length;return{ok:true,reason:box.complete?'所有階段完成':`已保存 ${expected.output}，下一階段：${box.recipe.runtimeSteps[box.stage].label}`}}
export function offerAddOn(box:ProjectBox,roll:number){if(roll>=box.customer.addOnChance||!box.recipe.addOns.length)return false;box.addOn={label:box.recipe.addOns[Math.floor(roll*1000)%box.recipe.addOns.length]};return true}
export function answerAddOn(box:ProjectBox,accept:boolean){if(!box.addOn)return{accepted:false,satisfaction:0};box.addOn.accepted=accept;if(accept){box.complete=false;box.recipe={...box.recipe,runtimeSteps:[...box.recipe.runtimeSteps,{...box.recipe.runtimeSteps.at(-1)!,index:box.recipe.runtimeSteps.length}]};return{accepted:true,satisfaction:8}}return{accepted:false,satisfaction:-8}}
export function upgradeEffects(career:Career):UpgradeEffects{const level=(id:string)=>career.upgrades[id]??0;return{capacity:{cpu:100+15*level('cpu'),gpu:100+15*level('gpu'),ram:100+15*level('ram'),context:100+18*level('context'),server:100+20*level('server')},speedMultiplier:1+level('context')*.02,stability:level('stability')*.08,caseSlots:1+level('case-slot'),agentLevel:career.agent.unlocked?career.agent.level:0}}
export function assignAgent(agent:AgentState,assignment:string|null,now:number){if(agent.busy)return{ok:false,reason:'Agent 正在處理任務，不可中途改派'};if(assignment&&!['text','art','code'].includes(assignment))return{ok:false,reason:'Agent 只支援文字、繪圖或程式'};if(now<agent.cooldownUntil)return{ok:false,reason:'Agent 冷卻中'};agent.assignment=assignment;return{ok:true,reason:assignment?'Agent 已指派':'Agent 正在休息'}}
export function agentCanProcess(agent:AgentState,box:ProjectBox,now:number){return !!agent.assignment&&!agent.busy&&now>=agent.cooldownUntil&&box.recipe.runtimeSteps.length===1&&box.recipe.runtimeSteps[0].stationId===agent.assignment}
export function processingMs(station:WorkstationData,model:ModelDefinition,serverLoad:number,effects:UpgradeEffects){const overload=1+Math.max(0,serverLoad-70)/80;return station.seconds*1000*overload*effects.speedMultiplier/Math.max(.65,model.speed)}
