import Phaser from 'phaser';
import './style.css';
import { models, type ModelDefinition } from './data/content';
import { drawModelChoices } from './core/modelDraw';
import { WorkstationScene, type RunResult } from './game/WorkstationScene';
import { saveCareer } from './services/save';
import { buyUpgrade, createCareer, recordLevel, type Career } from './core/career';
import { v1Levels, v1Upgrades, type LevelData } from './data/v1Catalog';
import { isLevelUnlocked } from './core/v1Runtime';
import { deleteCareer, loadCareers, exportCareer, previewImport } from './services/save';

const app=document.querySelector<HTMLDivElement>('#app')!; let game:Phaser.Game|undefined; let chosen:ModelDefinition|undefined; let activeCareer:Career|undefined;let selectedLevel:LevelData|undefined; const seed=Math.floor(Date.now()/86400000);
function shell(content:string){app.innerHTML=`<main class="shell">${content}</main>`}
async function menu(){const careers=await loadCareers().catch(()=>[]);shell(`<section class="hero"><div class="orb">AI</div><p class="eyebrow">WORKSTATION SIMULATION</p><h1>關於我重生為<br><strong>AI 模型的⋯</strong></h1><p class="subtitle">最棒的工作，就是不工作</p><button id="start">開始新生涯 <span>→</span></button><button class="ghost" id="import">匯入 JSON 備份</button><input id="import-file" type="file" accept="application/json,.json" hidden>${careers.map(c=>`<div class="career-row"><button class="ghost career" data-id="${c.id}">繼續：${c.name} · 紀元 ${c.era}</button><button class="delete" data-id="${c.id}" aria-label="刪除 ${c.name}">×</button></div>`).join('')}<p id="import-status" class="form-status" role="status"></p><footer>開發中 v0.3 · 完整第一版內容持續整合中</footer></section>`);document.querySelector('#start')!.addEventListener('click',pickModel);document.querySelectorAll<HTMLElement>('.career').forEach(el=>el.onclick=()=>{activeCareer=careers.find(c=>c.id===el.dataset.id);chosen=models.find(m=>m.id===activeCareer?.modelId);if(chosen)careerHub()});document.querySelectorAll<HTMLElement>('.delete').forEach(el=>el.onclick=async()=>{const career=careers.find(c=>c.id===el.dataset.id);if(career&&confirm(`刪除「${career.name}」？此動作無法復原。`)){await deleteCareer(career.id);menu()}});const input=document.querySelector<HTMLInputElement>('#import-file')!,status=document.querySelector<HTMLElement>('#import-status')!;document.querySelector('#import')!.addEventListener('click',()=>input.click());input.onchange=async()=>{try{const file=input.files?.[0];if(!file)return;const preview=previewImport(await file.text());if(!confirm(`匯入「${preview.name}」？\n模型：${models.find(m=>m.id===preview.modelId)?.name??preview.modelId}\n更新：${new Date(preview.updatedAt).toLocaleString()}\n\n相同存檔將被覆蓋。`))return;await saveCareer(preview.career);status.textContent='備份已匯入，正在載入…';await menu()}catch(error){status.textContent=`匯入失敗：${error instanceof Error?error.message:'檔案無法讀取'}`}}}
function pickModel(){const picks=drawModelChoices(seed);shell(`<section class="selection"><p class="eyebrow">BOOT SEQUENCE / 01</p><h2>選擇這次重生的模型</h2><p>每個模型都有上限與代價。選擇後外觀固定。</p><div class="cards">${picks.map(m=>`<button class="model" data-id="${m.id}" style="--accent:#${m.color.toString(16).padStart(6,'0')}"><span class="rarity">${m.rarity==='rare'?'稀有':'標準'} MODEL</span><i class="avatar">${m.name.slice(0,1)}</i><h3>${m.name}</h3><q>${m.tagline}</q><b>${m.strengths.join(' · ')}</b><small>代價：${m.weakness}</small><span class="select">選擇並建立獨立存檔</span></button>`).join('')}</div><button class="back" id="back">← 返回</button></section>`);document.querySelectorAll<HTMLElement>('.model').forEach(el=>el.onclick=async()=>{chosen=models.find(m=>m.id===el.dataset.id)!;activeCareer=createCareer(chosen.id,Date.now()>>>0,`${chosen.name} 生涯`);await saveCareer(activeCareer);careerHub()});document.querySelector('#back')!.addEventListener('click',menu)}
function careerHub(){const upgrades=v1Upgrades.filter(u=>u.era<=activeCareer!.era);shell(`<section class="result career-hub"><p class="eyebrow">CAREER SLOT</p><h2>${activeCareer!.name}</h2><p>紀元 ${activeCareer!.era} · ★ ${Object.values(activeCareer!.levels).reduce((n,l)=>n+l.stars,0)}</p><p>訂閱 ${activeCareer!.subscribers}　評價 ${activeCareer!.rating.toFixed(1)}　<b>運算點 ${activeCareer!.resources}</b></p><button id="levels">選擇正式關卡</button><h3>模型與工作站升級</h3><div class="upgrade-grid">${upgrades.map(u=>{const level=activeCareer!.upgrades[u.id]??0,cost=u.cost*(level+1),max=level>=u.maxLevel;return`<button class="upgrade" data-id="${u.id}" ${max||activeCareer!.resources<cost?'disabled':''}><span>${u.name} <b>Lv.${level}/${u.maxLevel}</b></span><small>${u.effect}${u.tradeoff?` · ${u.tradeoff}`:''}</small><strong>${max?'已滿級':`◈ ${cost}`}</strong></button>`}).join('')}</div>${activeCareer!.agent.unlocked?`<label class="agent-setting">Agent 指派<select id="agent-assignment"><option value="">休息（不佔用資源）</option><option value="text">文字單步任務</option><option value="art">繪圖單步任務</option><option value="code">程式單步任務</option></select></label>`:''}<p id="shop-status" class="form-status" role="status"></p><button class="ghost" id="backup">下載 JSON 備份</button><button class="ghost" id="home">切換模型存檔</button></section>`);document.querySelector('#levels')!.addEventListener('click',levelSelect);document.querySelector('#home')!.addEventListener('click',menu);document.querySelectorAll<HTMLElement>('.upgrade').forEach(el=>el.onclick=async()=>{if(buyUpgrade(activeCareer!,el.dataset.id!)){await saveCareer(activeCareer!);careerHub()}});const assignment=document.querySelector<HTMLSelectElement>('#agent-assignment');if(assignment){assignment.value=activeCareer!.agent.assignment??'';assignment.onchange=async()=>{activeCareer!.agent.assignment=assignment.value||null;activeCareer!.updatedAt=new Date().toISOString();await saveCareer(activeCareer!);document.querySelector('#shop-status')!.textContent=assignment.value?'指派已儲存，Agent 將在支援的關卡處理單步工作。':'Agent 已休息，停止佔用資源。'}}document.querySelector('#backup')!.addEventListener('click',()=>{const blob=new Blob([exportCareer(activeCareer!)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`${activeCareer!.id}.json`;a.click();URL.revokeObjectURL(a.href)})}
function levelSelect(){const eraNames=['','初生模型期','多工具模型期','複合專案期','Agent 協作期','高負載平台期'];shell(`<section class="level-select"><p class="eyebrow">47 LEVEL CAREER</p><h2>五個 AI 紀元</h2>${[1,2,3,4,5].map(era=>`<section class="era"><h3>紀元 ${era} · ${eraNames[era]}</h3><div class="level-grid">${v1Levels.filter(l=>l.era===era).map(level=>{const unlocked=isLevelUnlocked(activeCareer!,level),progress=activeCareer!.levels[level.id];return`<button class="level" data-id="${level.id}" ${unlocked?'':'disabled'}><b>${level.index}</b><span>${level.name}</span><small>${progress?.stars?'★'.repeat(progress.stars):unlocked?'未完成':'🔒 未解鎖'}</small></button>`}).join('')}</div></section>`).join('')}<button class="back" id="hub">← 生涯中心</button></section>`);document.querySelectorAll<HTMLElement>('.level:not(:disabled)').forEach(el=>el.onclick=()=>{selectedLevel=v1Levels.find(l=>l.id===el.dataset.id);startGame()});document.querySelector('#hub')!.addEventListener('click',careerHub)}
function startGame(){if(!selectedLevel)return levelSelect();app.innerHTML=`<main class="game-shell"><div id="game" aria-label="即時工作站遊戲區"></div><header class="game-top"><span class="live-dot" aria-hidden="true"></span><b>${chosen!.name}</b><span>${selectedLevel.name}</span></header><aside class="control-hint"><b>移動</b> WASD／方向鍵 <i></i><b>互動</b> E／空白鍵</aside><p class="rotate-hint">旋轉裝置以取得更寬廣的工作站視野</p></main>`;const scene=new WorkstationScene(chosen!,activeCareer!,selectedLevel.id,activeCareer!.seed+selectedLevel.index,finish);game=new Phaser.Game({type:Phaser.AUTO,parent:'game',backgroundColor:'#07101d',scene,scale:{mode:Phaser.Scale.FIT,autoCenter:Phaser.Scale.CENTER_BOTH,width:960,height:640},render:{antialias:true},input:{activePointers:3}})}
async function finish(result:RunResult){game?.destroy(true);game=undefined;if(!activeCareer)activeCareer=createCareer(chosen!.id,seed);recordLevel(activeCareer,selectedLevel!.id,result.score,result.stars,result.satisfaction,result.complaints[0]);await saveCareer(activeCareer);shell(`<section class="result"><p class="eyebrow">SHIFT COMPLETE</p><h2>${selectedLevel!.name}</h2><div class="stars">${[1,2,3].map(n=>`<span class="${n<=result.stars?'on':''}">★</span>`).join('')}</div><p class="big">${result.score}</p><p>完整交付 ${result.delivered} 份 · 滿意度 ${result.satisfaction} · 生涯已儲存</p><div class="quote">「伺服器終於可以休息。你也是。」</div><button id="again">再挑戰一次</button><button class="ghost" id="choose">選擇關卡</button><button class="ghost" id="hub">生涯中心</button></section>`);document.querySelector('#again')!.addEventListener('click',startGame);document.querySelector('#choose')!.addEventListener('click',levelSelect);document.querySelector('#hub')!.addEventListener('click',careerHub)}
menu(); if('serviceWorker'in navigator)window.addEventListener('load',()=>navigator.serviceWorker.register('./sw.js'));
