import Phaser from 'phaser';
import './style.css';
import { models, type ModelDefinition } from './data/content';
import { drawModelChoices } from './core/modelDraw';
import { WorkstationScene, type RunResult } from './game/WorkstationScene';
import { saveCareer } from './services/save';
import { createCareer, recordLevel, type Career } from './core/career';
import { loadCareers, exportCareer } from './services/save';

const app=document.querySelector<HTMLDivElement>('#app')!; let game:Phaser.Game|undefined; let chosen:ModelDefinition|undefined; let activeCareer:Career|undefined; const seed=Math.floor(Date.now()/86400000);
function shell(content:string){app.innerHTML=`<main class="shell">${content}</main>`}
async function menu(){const careers=await loadCareers().catch(()=>[]);shell(`<section class="hero"><div class="orb">AI</div><p class="eyebrow">WORKSTATION SIMULATION</p><h1>關於我重生為<br><strong>AI 模型的⋯</strong></h1><p class="subtitle">最棒的工作，就是不工作</p><button id="start">開始新生涯 <span>→</span></button>${careers.map(c=>`<button class="ghost career" data-id="${c.id}">繼續：${c.name} · 紀元 ${c.era}</button>`).join('')}<footer>開發中 v0.2 · 完整第一版內容持續整合中</footer></section>`);document.querySelector('#start')!.addEventListener('click',pickModel);document.querySelectorAll<HTMLElement>('.career').forEach(el=>el.onclick=()=>{activeCareer=careers.find(c=>c.id===el.dataset.id);chosen=models.find(m=>m.id===activeCareer?.modelId);if(chosen)careerHub()})}
function pickModel(){const picks=drawModelChoices(seed);shell(`<section class="selection"><p class="eyebrow">BOOT SEQUENCE / 01</p><h2>選擇這次重生的模型</h2><p>每個模型都有上限與代價。選擇後外觀固定。</p><div class="cards">${picks.map(m=>`<button class="model" data-id="${m.id}" style="--accent:#${m.color.toString(16).padStart(6,'0')}"><span class="rarity">${m.rarity==='rare'?'稀有':'標準'} MODEL</span><i class="avatar">${m.name.slice(0,1)}</i><h3>${m.name}</h3><q>${m.tagline}</q><b>${m.strengths.join(' · ')}</b><small>代價：${m.weakness}</small><span class="select">選擇並建立獨立存檔</span></button>`).join('')}</div><button class="back" id="back">← 返回</button></section>`);document.querySelectorAll<HTMLElement>('.model').forEach(el=>el.onclick=async()=>{chosen=models.find(m=>m.id===el.dataset.id)!;activeCareer=createCareer(chosen.id,Date.now()>>>0,`${chosen.name} 生涯`);await saveCareer(activeCareer);careerHub()});document.querySelector('#back')!.addEventListener('click',menu)}
function careerHub(){shell(`<section class="result"><p class="eyebrow">CAREER SLOT</p><h2>${activeCareer!.name}</h2><p>紀元 ${activeCareer!.era} · ★ ${Object.values(activeCareer!.levels).reduce((n,l)=>n+l.stars,0)}</p><p>訂閱 ${activeCareer!.subscribers}　評價 ${activeCareer!.rating.toFixed(1)}　運算點 ${activeCareer!.resources}</p><button id="play">進入下一班</button><button class="ghost" id="backup">下載 JSON 備份</button><button class="ghost" id="home">切換模型存檔</button></section>`);document.querySelector('#play')!.addEventListener('click',startGame);document.querySelector('#home')!.addEventListener('click',menu);document.querySelector('#backup')!.addEventListener('click',()=>{const blob=new Blob([exportCareer(activeCareer!)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`${activeCareer!.id}.json`;a.click();URL.revokeObjectURL(a.href)})}
function startGame(){app.innerHTML=`<div id="game"></div><div class="game-top"><b>${chosen!.name}</b><span>工作站連線中</span></div>`;const scene=new WorkstationScene(chosen!,seed,finish);game=new Phaser.Game({type:Phaser.AUTO,parent:'game',backgroundColor:'#0a1024',scene,scale:{mode:Phaser.Scale.FIT,autoCenter:Phaser.Scale.CENTER_BOTH,width:960,height:640},render:{antialias:true},input:{activePointers:3}})}
async function finish(result:RunResult){game?.destroy(true);game=undefined;if(!activeCareer)activeCareer=createCareer(chosen!.id,seed);recordLevel(activeCareer,'era1-01',result.score,result.stars,Math.min(100,55+result.delivered*8));await saveCareer(activeCareer);shell(`<section class="result"><p class="eyebrow">SHIFT COMPLETE</p><h2>今日運算結束</h2><div class="stars">${[1,2,3].map(n=>`<span class="${n<=result.stars?'on':''}">★</span>`).join('')}</div><p class="big">${result.score}</p><p>完整交付 ${result.delivered} 份專案 · 生涯已自動儲存</p><div class="quote">「伺服器終於可以休息。你也是。」</div><button id="again">再挑戰一次</button><button class="ghost" id="hub">生涯中心</button></section>`);document.querySelector('#again')!.addEventListener('click',startGame);document.querySelector('#hub')!.addEventListener('click',careerHub)}
menu(); if('serviceWorker'in navigator)window.addEventListener('load',()=>navigator.serviceWorker.register('./sw.js'));
